name: 6_graph

on:
  push:
    branches: [ main ]

jobs:
  build_1_post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pushes POST to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'docs/post'
          user-name: michelmetran
          user-email: michelmetran@gmail.com

          destination-github-username: 'gaemapiracicaba'
          destination-repository-name: 'gaemapiracicaba.github.io'
          target-branch: master
          target-directory: /_posts/diretrizes_vigilancia
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF

  build_2_imgs:
    runs-on: ubuntu-latest
    needs: [build_1_post]
    if: always()

    steps:
      - uses: actions/checkout@v2
      - name: Pushes IMGS to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'docs/imgs'
          user-name: michelmetran
          user-email: michelmetran@gmail.com

          destination-github-username: 'gaemapiracicaba'
          destination-repository-name: 'gaemapiracicaba.github.io'
          target-branch: master
          target-directory: /assets/diretrizes_vigilancia/imgs
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF

  build_3_graph:
    runs-on: ubuntu-latest
    needs: [build_1_post, build_2_imgs]
    if: always()

    steps:
      - uses: actions/checkout@v2
      - name: Pushes GRAPH to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'data/output/graph'
          user-name: michelmetran
          user-email: michelmetran@gmail.com

          destination-github-username: 'gaemapiracicaba'
          destination-repository-name: 'gaemapiracicaba.github.io'
          target-branch: master
          target-directory: /assets/diretrizes_vigilancia/graph
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
